#!/usr/local/bin/python3

# Tag commit messages with branch name for JIRA integrations.
# Replace .git/hooks/prepare-commit-message with this file

import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(['git', 'symbolic-ref', '--short', 'HEAD']).decode('ascii').strip()
regex = r'(\w{3,4}-\d{3,4})'

if re.match(regex, branch):
    issue = re.match(regex, branch).group(1)
    with open(commit_msg_filepath, 'r+') as fh:
        commit_msg = fh.read()
        fh.seek(0, 0)
        fh.write('[%s] %s' % (issue, commit_msg))
else:
    sys.stderr.write(f"Could not locate issue number in branch name: {branch}")
