#!/bin/bash

# cd to the git root
function gcd {
    cd $(git rev-parse --show-cdup)
}

function ptt {
    ssh bbsu@ptt.cc
}

function ports {
    lsof -PiTCP -sTCP:LISTEN
}

function load-profile {
    source ~/.bash_profile
}

function docker-prune-container {
    docker ps -a | awk '{if(NR>1 && !match($0, /Up [1-9]/)) print $1}' | xargs docker container rm
}

function of {
    lsof -nP +c 15 | grep LISTEN
}

function git-sync-upstream {
    git checkout master && git pull upstream master && git push origin master
}
